// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.SubdomainFinder
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("rootDomain")]
        public RootDomain RootDomain { get; set; }

        [JsonProperty("subDomains")]
        public SubDomain[] SubDomains { get; set; }

        [JsonProperty("count")]
        public long? Count { get; set; }

        [JsonProperty("totalFound")]
        public long? TotalFound { get; set; }
    }

    public partial class RootDomain
    {
        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("records")]
        public string[] Records { get; set; }
    }

    public partial class SubDomain
    {
        [JsonProperty("host")]
        public string Host { get; set; }

        [JsonProperty("records")]
        public string[] Records { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
